service: serverless-http-api-typescript-dynamodb

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

functions:
  test:
    handler: src/test.test
    events:
      - httpApi:
          path: /test
          method: get
