service: serverless-http-api-typescript-dynamodb

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

functions:
  merged:
    handler: src/handlers/merged.merged
    events:
      - httpApi:
          path: /merged
          method: get
